global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "prometheus:9090"

  - job_name: "pve-node"
    static_configs:
      - targets:
        - "pve.home.arpa:9100"

  - job_name: "docker-node"
    static_configs:
      - targets:
        - "docker-host.home.arpa:9100"
  - job_name: "docker-cadvisor"
    static_configs:
      - targets:
          - "docker-host.home.arpa:8081"
